version: "3"
services:
  pythonredis:
    image: kammana/python-redis:1.0
    ports:
      - "80:5000"
    networks:
      - javahome
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
  redis:
    image: redis:latest
    networks:
      - javahome
    deploy:
      replicas: 2
network:
  javahome:
